services:
  libft-dev:
    build: .
    container_name: libft-workspace
    volumes:
      - .:/home/libft/workspace
      - libft-home:/home/libft
    working_dir: /home/libft/workspace
    stdin_open: true
    tty: true
    command: /bin/bash

volumes:
  libft-home: