services:
  gaming-container:
    build: .
    container_name: gaming-env
    stdin_open: true
    tty: true
    
    # GPU access for 3D acceleration (using DRI for integrated/AMD graphics)
    
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/tmp/pulse-socket
      
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/pulse-socket:/tmp/pulse-socket:rw
      
      - ./game-data:/home/gamer/games
      - ./steam-data:/home/gamer/.steam
      - ./wine-data:/home/gamer/.wine
      
      - /dev/dri:/dev/dri
      
    network_mode: "host"
    
    privileged: false
    devices:
      - /dev/dri:/dev/dri
    
    security_opt:
      - seccomp:unconfined
    
    restart: unless-stopped
