services:
  gaming-benchmark:
    build: .
    container_name: steam-amd-container
    hostname: steam-amd
    privileged: true
    network_mode: host
    
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - AMD_VULKAN_ICD=RADV
      - RADV_PERFTEST=gpl
      
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri:rw
      - ~/.steam:/home/benchuser/.steam:rw
      
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
              
    stdin_open: true
    tty: true
    
    command: /bin/bash
